name: Deploy to quay.io on push to specific branches

on:
  push:
    branches:
      - master
      - releases/*
      - chores/*

jobs:
  build:
    if: ${{ github.repositoryUrl == 'jkilzi/assisted-ui-lib' }}
    name: Build
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Checkout assisted-ui-lib
        uses: actions/checkout@v3
        with:
          path: assisted-ui-lib

      - name: Checkout assisted-ui
        uses: actions/checkout@v3
        with:
          repository: openshift-assisted/assisted-ui
          path: assisted-ui

      - name: Build assisted-ui-lib
        working-directory: ./assisted-ui-lib
        run: |
          yarn install --frozen-lockfile
          node ./scripts/esbuild/prod.js
          yarn pack -f $GITHUB_WORKSPACE/openshift-assisted-ui-lib-v0.0.0.tgz

      - name: Build assisted-ui
        working-directory: ./assisted-ui
        run: |
          yarn add file:$GITHUB_WORKSPACE/openshift-assisted-ui-lib-v0.0.0.tgz
          yarn build

#      - name: Move into assisted-ui
#        run: |
#          cd ./assisted-ui
#          pwd

#      - name: Build image
#        id: build-image
#        env:
#          REACT_APP_GIT_SHA: ${GITHUB_SHA:0:8}
#          REACT_APP_VERSION: ${{ github.ref_name }}
#        uses: redhat-actions/buildah-build@v2
#        with:
#          image: assisted-installer-ui
#          tags: >
#            $REACT_APP_GIT_SHA
#            $REACT_APP_VERSION
#            latest
#          build-args: |
#            REACT_APP_GIT_SHA=$REACT_APP_GIT_SHA
#            REACT_APP_VERSION=$REACT_APP_VERSION
#          containerfiles: Dockerfile

#      - name: Push to Quay.io
#        id: push-to-quay
#        uses: redhat-actions/push-to-registry@v2.6
#        with:
#          image: ${{ steps.build-image.outputs.image }}
#          tags: ${{ steps.build-image.outputs.tags }}
#          registry: quay.io/jkilzi
#          username: ${{ secrets.QUAYIO_JKILZI_USERNAME }}
#          password: ${{ secrets.QUAYIO_JKILZI_PASSWORD }}
